# Generated by Django 5.1.4 on 2024-12-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Enter a detailed project description.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(help_text="Link to the project's GitHub repository."),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Enter the project title (e.g., Machine Learning Analysis).', max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Type of project (e.g., Data, Software).', max_length=50, unique=True)),
                ('github_link', models.URLField(help_text='Link to the related GitHub repository.')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the project type.', null=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Type',
                'verbose_name_plural': 'Project Types',
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('title',), name='title_case_insensitive_unique')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(help_text='Select the project type.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='afro_engine.projecttype'),
        ),
    ]
