# Generated by Django 5.1.4 on 2024-12-08 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_engine', '0002_alter_project_options_remove_project_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ['status'], 'verbose_name': 'Project Type', 'verbose_name_plural': 'Project Types'},
        ),
        migrations.RemoveConstraint(
            model_name='projecttype',
            name='title_case_insensitive_unique',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the project.', null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='status',
            field=models.CharField(choices=[('DA', 'Data Analysis'), ('SW', 'Software Development'), ('DV', 'DevOps'), ('ML', 'Machine Learning')], default='DA', help_text='Type of project (e.g., Data, Software).', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(default=1, help_text='Select the project type.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='afro_engine.projecttype'),
        ),
    ]
