# Generated by Django 5.1.4 on 2024-12-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_engine', '0003_alter_projecttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
