# Generated by Django 5.1.4 on 2024-12-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_engine', '0005_aboutus_contact_newsletter_project_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique slug for SEO-friendly URLs.', unique=True),
        ),
    ]
